[package]
name = "leptonic"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
leptos = { version = "0.4", features = ["csr", "nightly"] }
wasm-bindgen = "0.2"
web-sys = "0.3"

[dev-dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
log = "0.4"
