[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "demo.rs"

[dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
leptonic = { path = ".." }
leptos = { version = "0.4", features = ["csr", "nightly"] }
log = "0.4"
